# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8e0cfbd5a63c7c8031946487be7c8d733dbe6d63a3e06503904a4f7e995184312b891114e4d16f534bf00d76f73e4f14a945607672672bb22da6c85742de041

test:
  secret_key_base: 7dcfb9a5d103f544061795776f7d918078ec9e7461c62919cc359c961f1c64456c81a25d5e842524b8b0dcf6849736f64ad2d1be1a394b7733dcb99a915aa9b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
